[package]
name = "teratai-app-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
test-utils = ["teratai-filesystem/test-utils"]

[dependencies]
rusqlite.workspace = true
serde_json.workspace = true
sha2.workspace = true
teratai-contracts.workspace = true
teratai-filesystem = { path = "../filesystem" }
time.workspace = true

[dev-dependencies]
teratai-filesystem = { path = "../filesystem", features = ["test-utils"] }
